# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapaDomicilios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MapaDomicilios
  pod 'Kingfisher'
  pod 'Then'
  pod 'SwiftyHelpers'
  pod 'RxDataSources'
  pod 'RxSwift',    '~> 4.0.0'
  pod 'RxCocoa',    '~> 4.0.0'
  pod 'Moya/RxSwift', '~> 10.0.0'
  pod 'Moya-ObjectMapper/RxSwift', '~> 2.5'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SwiftSpinner'
  
  target 'MapaDomiciliosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapaDomiciliosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
